
TFG

Este es el codigo del tfg de Borja Jimeno

En esta primera celda vamos a definir todas las funciones y variables que necesitaremos para calcular el ritmo teórico. Cada función está explicada al inicio y cada variable tiene asociadas sus unidades en un comentario a la derecha.  

Para la realización de las funciones se ha tomado como referencia:  
-El pdf ('rateTutorial_MMartinez_TAE25.pdf)    
-El capítulo 7 de la Tesis de María ('tesisMaria_chap7.pdf')   
-El artículo 'Inelastic and Elastic Scattering of 187-Mev Electrons from Selected Even-Even Nuclei - Richard Helm - PHISICAL REVIEW VOLUME 104, NUMBER 5 DECEMBER 1, 1956'  
-Para calcular el Quenching Factor, Sección 4.3.2 de la tesis de Tamara Pardo Yanguas ('Tesis-Tamara.pdf')

In [1]:
import numpy as np
import math as m
import matplotlib.pyplot as plt
from scipy import special
from scipy.stats import norm

from funciones_ritmo_teorico import*
from funciones_ritmo_exp import*


plt.rcParams['font.size'] = 18



In [2]:
timeMax=72.9 
timeMin=255.5 
timeAvg=(timeMax+timeMin)/2.

mW_min=0.1 #masa wimp minima en GeV
mW_max=3

mWs=np.logspace(mW_min,mW_max,num=1000,endpoint=True)

E_min=1
E_max=6.1

ventana_min=1       #Anchura minima de la ventana de integracion (keV_ee)
refinado=0.1          #Valor del espaciado minimo de la rejilla Minimo 0.1 keV_ee

es=np.arange(E_min,E_max,refinado)
energias_i=es


    
print(energias_i)

aux=np.zeros(3)
lista_var_e=[]
for i in energias_i:

    energias_f=[]
    for j in es:
        if(j>=i+ventana_min):
            energias_f.append(j)
    energias_f=np.array(energias_f)     
        
    for j in energias_f:

        Ei=aux[0]=i
        Ef=aux[1]=j

        tiempo_exposicion=calcula_t_exposicion()
        masa_exposicion=calcula_m_exposicion()

        ritmo_comp=integral_exp(Ei,Ef,masa_exposicion,tiempo_exposicion)
        sigma_sis=np.array([(ritmo_comp/(totalRate_NaI_ee(Ei,Ef,timeAvg,a,1)*masa_exposicion*tiempo_exposicion/365)) for a in mWs])

        #print(min(sigma_sis))
        aux[2]=min(sigma_sis)
        #print(aux)
        lista_var_e.append(aux.copy())

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6. ]


/tmp/ipykernel_6601/2095623156.py:42: RuntimeWarning: divide by zero encountered in double_scalars
  sigma_sis=np.array([(ritmo_comp/(totalRate_NaI_ee(Ei,Ef,timeAvg,a,1)*masa_exposicion*tiempo_exposicion/365)) for a in mWs])


In [3]:
datos_variacion_energias=np.array(lista_var_e)
np.savetxt("Datos/array_minimos_ventanas.txt",datos_variacion_energias,delimiter=";")
print(datos_variacion_energias)

[[1.00000000e+00 2.00000000e+00 2.18771940e-42]
 [1.00000000e+00 2.10000000e+00 2.27684175e-42]
 [1.00000000e+00 2.20000000e+00 2.36865100e-42]
 ...
 [4.90000000e+00 5.90000000e+00 7.00176353e-41]
 [4.90000000e+00 6.00000000e+00 6.91570560e-41]
 [5.00000000e+00 6.00000000e+00 7.21160898e-41]]


In [4]:

E_min=1
E_max=6.1

ventana_min=1       #Anchura minima de la ventana de integracion (keV_ee)
refinado=0.1          #Valor del espaciado minimo de la rejilla Minimo 0.1 keV_ee

energias_i=np.arange(E_min,E_max,refinado)


comb=np.zeros((9),dtype=int)
lista=[]
for i1 in range (2):
    for i2 in range (2):
        for i3 in range (2):
            for i4 in range (2):
                    for i5 in range (2):
                        for i6 in range (2):
                            for i7 in range (2):
                                for i8 in range (2):
                                     comb[0]=i1
                                     comb[1]=i2
                                     comb[2]=i3
                                     comb[3]=i4
                                     comb[4]=i5
                                     comb[5]=i6
                                     comb[6]=i7
                                     comb[7]=i8
                                     lista.append(comb.copy())

lista2=[]
for j in range (len(lista)):
    if j>0:
         lista2.append(lista[j].copy())
     
array_detectores=np.array(lista2)                       
                                     
                                     
print(array_detectores)


[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]
 ...
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 1 0]]


In [5]:

lista_var_det=np.zeros(len(array_detectores))

Ei=1
Ef=6

for i in range(len(array_detectores)):
    tiempo_exposicion=calcula_t_exposicion(array_detectores[i])
    masa_exposicion=calcula_m_exposicion(array_detectores[i])

    ritmo_comp=integral_exp(Ei,Ef,masa_exposicion,tiempo_exposicion,array_det=array_detectores[i])
    sigma_sis=np.array([(ritmo_comp/(totalRate_NaI_ee(Ei,Ef,timeAvg,a,1)*masa_exposicion*tiempo_exposicion/365)) for a in mWs])

    #print(min(sigma_sis))
    lista_var_det[i]=min(sigma_sis)

/tmp/ipykernel_6601/1072837613.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  sigma_sis=np.array([(ritmo_comp/(totalRate_NaI_ee(Ei,Ef,timeAvg,a,1)*masa_exposicion*tiempo_exposicion/365)) for a in mWs])


In [7]:
datos_variacion_detectores=lista_var_det
np.savetxt("Datos/array_minimos_detectores.txt",datos_variacion_detectores,delimiter=";")



np.savetxt("Datos/array_detectores.txt",array_detectores,delimiter=";")


