In [ ]:
import numpy as np
import math as m
import matplotlib.pyplot as plt
from scipy import special
from scipy.stats import norm

from funciones_ritmo_teorico import*
from funciones_ritmo_exp import*


plt.rcParams['font.size'] = 18


[array([0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 1, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 1, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 1, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 1, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 0]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 1, 1, 0]),
 